module.exports = [
  { word: 'ephemeral', definition: 'Lasting for a very short time', phonetic: '/ɪˈfem.ər.əl/' },
  { word: 'eloquent', definition: 'Fluent or persuasive in speaking or writing', phonetic: '/ˈel.ə.kwənt/' },
  { word: 'benevolent', definition: 'Well-meaning and kindly', phonetic: '/bəˈnev.əl.ənt/' },
  { word: 'frugal', definition: 'Sparing or economical with regard to money or food', phonetic: '/ˈfruː.ɡəl/' },
  { word: 'pragmatic', definition: 'Dealing with things sensibly and realistically', phonetic: '/præɡˈmæt.ɪk/' },
  { word: 'resilient', definition: 'Able to recover quickly from difficult conditions', phonetic: '/rɪˈzɪl.i.ənt/' },
  { word: 'ambiguous', definition: 'Open to more than one interpretation', phonetic: '/æmˈbɪɡ.ju.əs/' },
  { word: 'candid', definition: 'Truthful and straightforward; frank', phonetic: '/ˈkæn.dɪd/' },
  { word: 'diligent', definition: 'Having or showing care in one\'s work or duties', phonetic: '/ˈdɪl.ɪ.dʒənt/' },
  { word: 'empathy', definition: 'The ability to understand and share the feelings of another', phonetic: '/ˈem.pə.θi/' },
  { word: 'gratitude', definition: 'The quality of being thankful', phonetic: '/ˈɡræt.ɪ.tjuːd/' },
  { word: 'hypothetical', definition: 'Based on assumed or imagined situations', phonetic: '/ˌhaɪ.pəˈθet.ɪ.kəl/' },
  { word: 'inevitable', definition: 'Certain to happen; unavoidable', phonetic: '/ɪˈnev.ɪ.tə.bəl/' },
  { word: 'juxtapose', definition: 'To place close together for contrasting effect', phonetic: '/ˈdʒʌk.stə.pəʊz/' },
  { word: 'lucid', definition: 'Expressed clearly; easy to understand', phonetic: '/ˈluː.sɪd/' },
  { word: 'meticulous', definition: 'Showing great attention to detail; very careful', phonetic: '/məˈtɪk.jə.ləs/' },
  { word: 'nostalgia', definition: 'A sentimental longing for the past', phonetic: '/nɒˈstæl.dʒə/' },
  { word: 'optimistic', definition: 'Hopeful and confident about the future', phonetic: '/ˌɒp.tɪˈmɪs.tɪk/' },
  { word: 'persevere', definition: 'To continue in a course of action despite difficulty', phonetic: '/ˌpɜː.sɪˈvɪər/' },
  { word: 'quintessential', definition: 'Representing the most perfect example of something', phonetic: '/ˌkwɪn.tɪˈsen.ʃəl/' },
  { word: 'reluctant', definition: 'Unwilling and hesitant; disinclined', phonetic: '/rɪˈlʌk.tənt/' },
  { word: 'skeptical', definition: 'Not easily convinced; having doubts', phonetic: '/ˈskep.tɪ.kəl/' },
  { word: 'tenacious', definition: 'Tending to keep a firm hold; persistent', phonetic: '/təˈneɪ.ʃəs/' },
  { word: 'ubiquitous', definition: 'Present, appearing, or found everywhere', phonetic: '/juːˈbɪk.wɪ.təs/' },
  { word: 'versatile', definition: 'Able to adapt or be adapted to many functions', phonetic: '/ˈvɜː.sə.taɪl/' },
  { word: 'whimsical', definition: 'Playfully quaint or fanciful; unpredictable', phonetic: '/ˈwɪm.zɪ.kəl/' },
  { word: 'zealous', definition: 'Having great energy or enthusiasm for a cause', phonetic: '/ˈzel.əs/' },
  { word: 'abstract', definition: 'Dealing with ideas rather than physical reality', phonetic: '/ˈæb.strækt/' },
  { word: 'brevity', definition: 'Concise and exact use of words; shortness of time', phonetic: '/ˈbrev.ɪ.ti/' },
  { word: 'compelling', definition: 'Evoking interest or attention in a powerfully irresistible way', phonetic: '/kəmˈpel.ɪŋ/' },
  { word: 'deteriorate', definition: 'To become progressively worse', phonetic: '/dɪˈtɪə.ri.ə.reɪt/' },
  { word: 'elaborate', definition: 'Involving many carefully arranged parts; detailed', phonetic: '/ɪˈlæb.ər.ət/' },
  { word: 'fluctuate', definition: 'To rise and fall irregularly in number or amount', phonetic: '/ˈflʌk.tʃu.eɪt/' },
  { word: 'gregarious', definition: 'Fond of company; sociable', phonetic: '/ɡrɪˈɡeə.ri.əs/' },
  { word: 'hinder', definition: 'To create difficulties resulting in delay', phonetic: '/ˈhɪn.dər/' },
  { word: 'impeccable', definition: 'In accordance with the highest standards; faultless', phonetic: '/ɪmˈpek.ə.bəl/' },
  { word: 'jubilant', definition: 'Feeling or expressing great happiness and triumph', phonetic: '/ˈdʒuː.bɪ.lənt/' },
  { word: 'kindle', definition: 'To light or set on fire; to arouse or inspire', phonetic: '/ˈkɪn.dəl/' },
  { word: 'languid', definition: 'Displaying a lack of physical or mental energy', phonetic: '/ˈlæŋ.ɡwɪd/' },
  { word: 'magnanimous', definition: 'Very generous or forgiving, especially toward a rival', phonetic: '/mæɡˈnæn.ɪ.məs/' },
  { word: 'negligent', definition: 'Failing to take proper care; careless', phonetic: '/ˈneɡ.lɪ.dʒənt/' },
  { word: 'obsolete', definition: 'No longer produced or used; out of date', phonetic: '/ˈɒb.sə.liːt/' },
  { word: 'plausible', definition: 'Seeming reasonable or probable; convincing', phonetic: '/ˈplɔː.zə.bəl/' },
  { word: 'replenish', definition: 'To fill something up again; restore to a former level', phonetic: '/rɪˈplen.ɪʃ/' },
  { word: 'spontaneous', definition: 'Performed or occurring without premeditation', phonetic: '/spɒnˈteɪ.ni.əs/' },
  { word: 'tranquil', definition: 'Free from disturbance; calm and peaceful', phonetic: '/ˈtræŋ.kwɪl/' },
  { word: 'unanimous', definition: 'Fully in agreement; sharing the same opinion', phonetic: '/juːˈnæn.ɪ.məs/' },
  { word: 'vivid', definition: 'Producing powerful feelings or strong images in the mind', phonetic: '/ˈvɪv.ɪd/' },
  { word: 'wary', definition: 'Feeling or showing caution about possible dangers', phonetic: '/ˈweə.ri/' },
  { word: 'yearn', definition: 'To have an intense feeling of longing for something', phonetic: '/jɜːn/' },
];
