module.exports = [
  { word: 'efímero', definition: 'Que dura muy poco tiempo', phonetic: '/eˈfi.me.ɾo/' },
  { word: 'elocuente', definition: 'Que habla o escribe con fluidez y persuasión', phonetic: '/e.loˈkwen.te/' },
  { word: 'benévolo', definition: 'Que tiene buena voluntad hacia los demás', phonetic: '/beˈne.βo.lo/' },
  { word: 'frugal', definition: 'Que come o gasta con moderación', phonetic: '/fɾuˈɣal/' },
  { word: 'pragmático', definition: 'Que actúa de forma práctica y realista', phonetic: '/pɾaɣˈma.ti.ko/' },
  { word: 'resiliente', definition: 'Capaz de adaptarse y recuperarse ante la adversidad', phonetic: '/re.siˈljen.te/' },
  { word: 'ambiguo', definition: 'Que puede interpretarse de varias maneras', phonetic: '/amˈbi.ɣwo/' },
  { word: 'cándido', definition: 'Ingenuo, sincero, sin malicia', phonetic: '/ˈkan.di.do/' },
  { word: 'diligente', definition: 'Que actúa con cuidado y dedicación', phonetic: '/di.liˈxen.te/' },
  { word: 'empatía', definition: 'Capacidad de identificarse con los sentimientos ajenos', phonetic: '/em.paˈti.a/' },
  { word: 'gratitud', definition: 'Sentimiento de agradecimiento', phonetic: '/ɡɾa.tiˈtud/' },
  { word: 'hipotético', definition: 'Que se basa en suposiciones o situaciones imaginarias', phonetic: '/i.poˈte.ti.ko/' },
  { word: 'inevitable', definition: 'Que no se puede evitar', phonetic: '/i.ne.βiˈta.ble/' },
  { word: 'yuxtaponer', definition: 'Poner algo junto a otra cosa para compararlas', phonetic: '/ʝuks.ta.poˈneɾ/' },
  { word: 'lúcido', definition: 'Que piensa y se expresa con claridad', phonetic: '/ˈlu.θi.ðo/' },
  { word: 'meticuloso', definition: 'Que presta gran atención a los detalles', phonetic: '/me.ti.kuˈlo.so/' },
  { word: 'nostalgia', definition: 'Añoranza o tristeza por el pasado', phonetic: '/nosˈtal.xja/' },
  { word: 'optimista', definition: 'Que tiende a ver el lado positivo de las cosas', phonetic: '/op.tiˈmis.ta/' },
  { word: 'perseverar', definition: 'Mantenerse firme en un propósito a pesar de las dificultades', phonetic: '/peɾ.se.βeˈɾaɾ/' },
  { word: 'esencial', definition: 'Que es fundamental o necesario', phonetic: '/e.senˈθjal/' },
  { word: 'reacio', definition: 'Que muestra resistencia a hacer algo', phonetic: '/reˈa.θjo/' },
  { word: 'escéptico', definition: 'Que duda de la verdad o certeza de algo', phonetic: '/esˈθep.ti.ko/' },
  { word: 'tenaz', definition: 'Que se mantiene firme en sus objetivos', phonetic: '/teˈnaθ/' },
  { word: 'ubicuo', definition: 'Que está presente en todas partes al mismo tiempo', phonetic: '/uˈβi.kwo/' },
  { word: 'versátil', definition: 'Que se adapta fácilmente a distintas funciones', phonetic: '/beɾˈsa.til/' },
  { word: 'caprichoso', definition: 'Que actúa por antojos o impulsos', phonetic: '/ka.pɾiˈtʃo.so/' },
  { word: 'fervoroso', definition: 'Que muestra gran entusiasmo o pasión', phonetic: '/feɾ.βoˈɾo.so/' },
  { word: 'abstracto', definition: 'Que se refiere a ideas en lugar de cosas concretas', phonetic: '/absˈtɾak.to/' },
  { word: 'brevedad', definition: 'Corta duración o extensión', phonetic: '/bɾe.βeˈðad/' },
  { word: 'convincente', definition: 'Que logra persuadir o generar credibilidad', phonetic: '/kom.binˈθen.te/' },
  { word: 'deteriorar', definition: 'Empeorar progresivamente algo', phonetic: '/de.te.ɾjoˈɾaɾ/' },
  { word: 'elaborado', definition: 'Que tiene muchas partes o detalles cuidados', phonetic: '/e.la.βoˈɾa.ðo/' },
  { word: 'fluctuar', definition: 'Variar de forma irregular en cantidad o intensidad', phonetic: '/flukˈtwaɾ/' },
  { word: 'gregario', definition: 'Que prefiere vivir o actuar en grupo', phonetic: '/ɡɾeˈɣa.ɾjo/' },
  { word: 'obstaculizar', definition: 'Poner dificultades o impedimentos', phonetic: '/obs.ta.ku.liˈθaɾ/' },
  { word: 'impecable', definition: 'Que no tiene ningún defecto', phonetic: '/im.peˈka.ble/' },
  { word: 'jubiloso', definition: 'Que siente o expresa gran alegría', phonetic: '/xu.βiˈlo.so/' },
  { word: 'encender', definition: 'Prender fuego o avivar una emoción', phonetic: '/en.θenˈdeɾ/' },
  { word: 'lánguido', definition: 'Falto de energía o vitalidad', phonetic: '/ˈlaŋ.ɡi.ðo/' },
  { word: 'magnánimo', definition: 'Que perdona con generosidad', phonetic: '/maɣˈna.ni.mo/' },
  { word: 'negligente', definition: 'Que no cumple con su deber por descuido', phonetic: '/ne.ɣliˈxen.te/' },
  { word: 'obsoleto', definition: 'Que ya no se usa o está desactualizado', phonetic: '/ob.soˈle.to/' },
  { word: 'plausible', definition: 'Que parece razonable o creíble', phonetic: '/plawˈsi.ble/' },
  { word: 'reponer', definition: 'Volver a poner algo o recuperar fuerzas', phonetic: '/re.poˈneɾ/' },
  { word: 'espontáneo', definition: 'Que surge de forma natural sin planificación', phonetic: '/es.ponˈta.ne.o/' },
  { word: 'tranquilo', definition: 'Libre de perturbaciones, en calma', phonetic: '/tɾaŋˈki.lo/' },
  { word: 'unánime', definition: 'Que comparte la misma opinión o sentimiento', phonetic: '/uˈna.ni.me/' },
  { word: 'vívido', definition: 'Que produce imágenes o sensaciones intensas', phonetic: '/ˈbi.βi.ðo/' },
  { word: 'cauto', definition: 'Que actúa con precaución para evitar peligros', phonetic: '/ˈkaw.to/' },
  { word: 'anhelar', definition: 'Desear algo con mucha intensidad', phonetic: '/a.neˈlaɾ/' },
];
